INSERT INTO NapredneBaza.Employees (Id, FirstName, LastName, JobTitle, DateOfHire, DepartmentId) VALUES (106648, 'Thomas', 'Evans', 'Technical Specialist', '2014-04-25', 5);
INSERT INTO NapredneBaza.Employees (Id, FirstName, LastName, JobTitle, DateOfHire, DepartmentId) VALUES (151116, 'Monica', 'Walters', 'Customer Service', '2017-06-28', 9);
INSERT INTO NapredneBaza.Employees (Id, FirstName, LastName, JobTitle, DateOfHire, DepartmentId) VALUES (152553, 'John', 'Smith', 'Brand Manager', '2010-12-16', 1);
INSERT INTO NapredneBaza.Employees (Id, FirstName, LastName, JobTitle, DateOfHire, DepartmentId) VALUES (157791, 'Sarah', 'Wilson', 'Sales Associate', '2015-06-29', 3);
INSERT INTO NapredneBaza.Employees (Id, FirstName, LastName, JobTitle, DateOfHire, DepartmentId) VALUES (218159, 'Christine', 'Sutherland', 'Sales Analyst', '2013-08-21', 3);
INSERT INTO NapredneBaza.Employees (Id, FirstName, LastName, JobTitle, DateOfHire, DepartmentId) VALUES (282677, 'Sonny', 'Leach', 'Web Developer', '2018-12-21', 5);
INSERT INTO NapredneBaza.Employees (Id, FirstName, LastName, JobTitle, DateOfHire, DepartmentId) VALUES (377418, 'Austin', 'Wong', 'SQL Developer', '2019-05-15', 5);
INSERT INTO NapredneBaza.Employees (Id, FirstName, LastName, JobTitle, DateOfHire, DepartmentId) VALUES (405436, 'Sophia', 'Jones', 'Brand Manager', '2011-07-28', 7);
INSERT INTO NapredneBaza.Employees (Id, FirstName, LastName, JobTitle, DateOfHire, DepartmentId) VALUES (488646, 'Nadia', 'Riggs', 'Quality Engineer', '2015-09-10', 1);
INSERT INTO NapredneBaza.Employees (Id, FirstName, LastName, JobTitle, DateOfHire, DepartmentId) VALUES (537977, 'Garry', 'Klein', 'Economist', '2012-11-12', 2);
INSERT INTO NapredneBaza.Employees (Id, FirstName, LastName, JobTitle, DateOfHire, DepartmentId) VALUES (564252, 'Jessica', 'Ellis', 'Supervisors', '2015-06-04', 6);
INSERT INTO NapredneBaza.Employees (Id, FirstName, LastName, JobTitle, DateOfHire, DepartmentId) VALUES (627432, 'Charles', 'Martin', 'Electrical Engineer', '2019-10-11', 1);
INSERT INTO NapredneBaza.Employees (Id, FirstName, LastName, JobTitle, DateOfHire, DepartmentId) VALUES (672124, 'Tracy', 'Davis', 'Data Analyst', '2017-10-17', 8);
INSERT INTO NapredneBaza.Employees (Id, FirstName, LastName, JobTitle, DateOfHire, DepartmentId) VALUES (676607, 'Lauren', 'O''Brien', 'Accountant', '2011-09-19', 2);
INSERT INTO NapredneBaza.Employees (Id, FirstName, LastName, JobTitle, DateOfHire, DepartmentId) VALUES (720297, 'Cory', 'Snyder', 'Bookkeeper', '2014-09-30', 2);
INSERT INTO NapredneBaza.Employees (Id, FirstName, LastName, JobTitle, DateOfHire, DepartmentId) VALUES (783141, 'Melina', 'Duncan', 'Sales Representative', '2010-10-22', 3);
INSERT INTO NapredneBaza.Employees (Id, FirstName, LastName, JobTitle, DateOfHire, DepartmentId) VALUES (799012, 'T-Jay', 'Mac', 'Dispatcher', '2015-04-12', 9);
INSERT INTO NapredneBaza.Employees (Id, FirstName, LastName, JobTitle, DateOfHire, DepartmentId) VALUES (810911, 'Haider', 'Hunter', 'Customer Service', '2013-09-11', 9);
INSERT INTO NapredneBaza.Employees (Id, FirstName, LastName, JobTitle, DateOfHire, DepartmentId) VALUES (917924, 'Jennifer', 'Roberts', 'Generalist', '2016-08-01', 4);
INSERT INTO NapredneBaza.Employees (Id, FirstName, LastName, JobTitle, DateOfHire, DepartmentId) VALUES (953874, 'James', 'White', 'Operations Director', '2013-03-17', 6);